language: java
jdk:
  - oraclejdk8
before_deploy:
  - "./gradlew shadowJar"
deploy:
  skip_cleanup: true
  provider: lambda
  function_name: niceOne
  role: arn:aws:iam::606926053612:role/lambda_basic_execution
  handler_name: net.enoot.niceone.NiceOneSpeechletRequestStreamHandler
  access_key_id:
    secure: IHsvelS8jrr6coYCk1yIhbAoOyYHc28Qf8MXiINCf6bkh1+qPUF1x+WdOEKjMg8KUtRDLi5vCviFzH+n0OJkax6M/gux3v8JLO/dEd/yunOOZFl9t1RqwCxxIlbg1hApFrVnVtPpWwUj3JcqTAwPQfag7PmQP21IaNrK63oi7grmyIPiqa8PJfNh/ilVp4EGND7m2Oxm+AsuoM0Otq4MskZ4aOvqhHWFWWIB5z6rfbX41NanFDH1/IYVmZ+IJVD0dMd0hDHo7GqmpyF7vJi40UCj/A7j/xtvp18tYxP7cX8eC85bIEHxT9elUYpBPh80gkvsx1n4/0ww2KxnnBLj8R/agYKdV+Q+5hDvkyMrKKTXYwbkgmIAueGwTWuoENwgSPOAxl4hFPx4WbtmClRMBApCJ9gEDqq1Mprc09bWvGh6/8QoQmCBmXJOeagdLPVb+tnFFJcgGslHN8q5wQB19yr98gfjeVIBkp7MqZmsHH/f7JKjos+fZFi6ta3ayFCyrm0pYJWa76exwJjkoToX7ngYweYdPUQU0POrnZeF1Kres7Ukzm7QLOMePmEAuUh7Jj2ogsVGC2Oh/mEKVMaynV1A2VFJbpCt5JC6CyMw142T99qjq5ZVnG2MIw5O6MUfI+/l9SkyO79W1nHqu4q009h40hhvll16wIlgIOiNZ30=
  secret_access_key:
    secure: QaqMyYB3Q0T4A1FW8YKjRjzTEfPw5xsqtigITiMAODx9avMfxf7dJnyYwqS073OVYRZNXu6BNRQpEf2bTOErUT4/rDm3DHQxAzh1zKO1sBcxlBwCMEoi1XhycyEu78teT4cxQSEkhX6ezxibwGL/7eZ1MD4Ydwpy9zVcCzr6f1n7GNlDzvdATlWGVkjxtQPfHpky1uCWVdr/he1ownwDXttg2aP7faKL5mu4BcOH2wvU5uZhaWftDVrkf8De99eI8kJVmZCcxUxuTlTJoKPSaEFaj9ldpqsSCLv/NaD7TosqYj3gEdHIeTc45lCKQDJpR/MxntTA/rguhvELVW8MXt0BAc9tQrVl2M4aOc5JojClk81NoRodpXwnyEqL8uquaobXlpPQwteV2yZSZ71Pv6Vw47BHd34LwCtRP/zAy8+YCryqpyy5kKRD+XsT5nDhfonj1fxwaKjJMtaAgumLE5mkwMNiYPCjoyC3gk+4JtYIUzUEcexqZlGD+K1T5mlagQnpBkr/Pds6gmMVfkuIkOtK1Rbp64DDR/QIfFSuM8Dq4t9hVRJPEaoC7/EDKpKh3r+5aX6SvwfXa6B7Thh2/6qzh4/FFLUbvZhGE4I5YT8gJhz59KRAVJx4kFIO4kbD+JqOcytvNKTNeJDpaPOCw3mdTTj9KAcsBdtg2UGugE8=
